feature: ['feature/*', 'feat/*', 'feature-*', 'feat-*']
bug: ['fix/*', 'fix-*']
chore: ['chore/*', 'chore-*']
refactor: ['refactor/*', 'refactoring/*', 'refactor-*', 'refactoring-*']
documentation: ['documentation/*', 'doc/*', 'documentation-*', 'doc-*']
